services:
  keycloak:
    environment:
      KC_HOSTNAME: "10.0.0.1"

  gateway:
    build: ./gateway
    hostname: gateway
    env_file: .env
    ports:
      - "${GATEWAY_HOST_PORT}:8080"
    networks:
      - devnet
    depends_on:
      keycloak:
        condition: service_healthy

  rest-api:
    build: ./rest-api
    hostname: rest-api
    env_file: .env
    ports:
      - "${REST_API_HOST_PORT}:8081"
    networks:
      - devnet
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy