services:
  s3garage:
    image: dxflrs/garage:v2.2.0
    hostname: ${GARAGE_API_INTERNAL_HOSTNAME:-s3garage}
    restart: unless-stopped
    ports:
      - "${GARAGE_API_HOST_PORT:-3900}:${GARAGE_API_INTERNAL_PORT:-3900}"
      - "${GARAGE_ADMIN_HOST_PORT:-3910}:${GARAGE_ADMIN_INTERNAL_PORT:-3910}"
    networks:
      - devnet
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - garage_data:/var/lib/garage/data
      - garage_meta:/var/lib/garage/meta
    environment:
      - GARAGE_RPC_SECRET=${GARAGE_RPC_SECRET}
      - GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN}
      - GARAGE_METRICS_TOKEN=${GARAGE_METRICS_TOKEN}

  s3garage-ui:
    image: khairul169/garage-webui:latest
    hostname: ${GARAGE_UI_INTERNAL_HOSTNAME:-s3garage-ui}
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
    ports:
      - "${GARAGE_UI_HOST_PORT:-3920}:${GARAGE_UI_INTERNAL_PORT:-3909}"
    networks:
      - devnet
    environment:
      - API_BASE_URL=http://${GARAGE_API_INTERNAL_HOSTNAME:-s3garage}:${GARAGE_ADMIN_INTERNAL_PORT:-3910}
      - API_ADMIN_KEY=${GARAGE_ADMIN_TOKEN}
      - S3_ENDPOINT_URL=http://${GARAGE_API_INTERNAL_HOSTNAME:-s3garage}:${GARAGE_API_INTERNAL_PORT:-3900}
      - S3_REGION=${GARAGE_REGION:-garage}

  s3-init:
    image: docker.io/alpine:3.23
    depends_on:
      s3garage:
        condition: service_started
    network_mode: service:s3garage
    pid: service:s3garage
    volumes:
      - ./garage/init.sh:/init.sh:ro
    environment:
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
      GARAGE_ADMIN_TOKEN: ${GARAGE_ADMIN_TOKEN}
      GARAGE_ACCESS_KEY_ID: ${GARAGE_ACCESS_KEY_ID}
      GARAGE_ACCESS_KEY_SECRET: ${GARAGE_ACCESS_KEY_SECRET}
      GARAGE_BUCKET_NAME: ${GARAGE_BUCKET_NAME}
      GARAGE_KEY_NAME: ${GARAGE_KEY_NAME}
      # for awscli used in init.sh
      AWS_ACCESS_KEY_ID: ${GARAGE_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${GARAGE_ACCESS_KEY_SECRET}
      AWS_DEFAULT_REGION: ${GARAGE_REGION:-garage}
    restart: on-failure:3
    entrypoint: ["/bin/sh", "/init.sh"]

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    hostname: ${KEYCLOAK_INTERNAL_HOSTNAME:-keycloak}
    env_file: .env
    environment:
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true" # Enable non secure HTTP for development
      KC_HOSTNAME: ${HOST_NAME}
      KC_HTTP_PORT: ${KEYCLOAK_HOST_PORT:-8180}
      KC_HTTP_MANAGEMENT_PORT: ${KEYCLOAK_MANAGEMENT_PORT:-8181}
      KC_HOSTNAME_STRICT: "false" # Allow requests from non-specifed domain in dev env (e.g. localhost:port)
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${POSTGRES_INTERNAL_HOSTNAME:-postgres}:${POSTGRES_INTERNAL_PORT:-5432}/${KEYCLOAK_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/export:/tmp/export
    ports:
      - ${KEYCLOAK_HOST_PORT:-8180}:${KEYCLOAK_INTERNAL_PORT:-8180}
      - ${KEYCLOAK_MANAGEMENT_HOST_PORT:-8181}:${KEYCLOAK_MANAGEMENT_INTERNAL_PORT:-8181}
    networks:
      - devnet
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      # Keycloak container does not have any CLI HTTP clients installed:
      # https://www.keycloak.org/observability/health#_healthcheck
      # https://stackoverflow.com/questions/58168955/testing-minimal-docker-containers-with-healthcheck/76790330#76790330
      # https://www.reddit.com/r/KeyCloak/comments/14a5a1y/how_to_enable_healthcheck_on_keycloak_on/
      test:
        - "CMD"
        - "bash"
        - "-c"
        - |
          exec 3<>/dev/tcp/127.0.0.1/8181
          printf 'GET /health HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3
          cat <&3 | grep '200'
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 120s # longer time when sql instead of h2 db
    command: start
  
  keycloak-config:
    image: adorsys/keycloak-config-cli:latest-26
    env_file: .env
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - devnet
    volumes:
      - ./keycloak/import:/config:ro
    environment:
      KEYCLOAK_URL: http://${KEYCLOAK_INTERNAL_HOSTNAME:-keycloak}:${KEYCLOAK_INTERNAL_PORT:-8180}
      KEYCLOAK_USER: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-coolture-dev}
      KEYCLOAK_TEST_USERS_PASSWORD: ${KEYCLOAK_TEST_USERS_PASSWORD:-admin}
      KEYCLOAK_COOLTURE_SWAGGER_CLIENT_ID: ${KEYCLOAK_COOLTURE_SWAGGER_CLIENT_ID:-coolture-swagger}
      KEYCLOAK_COOLTURE_SWAGGER_CLIENT_SECRET: ${KEYCLOAK_COOLTURE_SWAGGER_CLIENT_SECRET:-74in9eNuLAKHEIowc8LheU4CQv3pPx5x}
      KEYCLOAK_COOLTURE_GATEWAY_CLIENT_ID: ${KEYCLOAK_COOLTURE_GATEWAY_CLIENT_ID:-coolture-gateway}
      KEYCLOAK_COOLTURE_GATEWAY_CLIENT_SECRET: ${KEYCLOAK_COOLTURE_GATEWAY_CLIENT_SECRET:-YsiygIl2YKRzEyTW7UDnio05PpC8yQdJ}
      KEYCLOAK_COOLTURE_BOT_CLIENT_ID: ${KEYCLOAK_COOLTURE_BOT_CLIENT_ID:-coolture-bot}
      KEYCLOAK_COOLTURE_BOT_CLIENT_SECRET: ${KEYCLOAK_COOLTURE_BOT_CLIENT_SECRET:-HgT7kLmNpQrSvWxYzA3dBcEfJuK1o8i2}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
 
      IMPORT_FILES_LOCATIONS: '/config/*.yml'
      IMPORT_VAR_SUBSTITUTION_ENABLED: "true" # basic syntax is $(var_origin:VAR_NAME)
    restart: "no" # one-shot

  rabbitmq:
    image: rabbitmq:4-management-alpine
    hostname: ${RABBITMQ_INTERNAL_HOSTNAME:-rabbitmq}
    ports:
      - "${RABBITMQ_HOST_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_HOST_PORT:-15672}:15672"
    networks:
      - devnet
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    build: ./db
    hostname: ${POSTGRES_INTERNAL_HOSTNAME:-postgres}
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-coolture_db}
      KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak}
      KEYCLOAK_DB_USER: ${KEYCLOAK_DB_USER:-keycloak}
      KEYCLOAK_DB_NAME: ${KEYCLOAK_DB_NAME:-keycloak}
      EMBEDDING_VECTOR_DIM: ${EMBEDDING_VECTOR_DIM:-768}
    volumes:
      # from postgres 18, data is stored in /var/lib/postgresql instead of /var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    ports:
      - ${POSTGRES_HOST_PORT:-5430}:${POSTGRES_INTERNAL_PORT:-5432}
    networks:
      - devnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-coolture_db} -h localhost -p ${POSTGRES_INTERNAL_PORT:-5432}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  keycloak_data:
  garage_data:
  garage_meta:
  postgres_data:

networks:
  devnet:
    external: true
    name: coolture-core_devnet
