server:
  port: ${GATEWAY_INTERNAL_PORT:8080}
  servlet:
    session:
      cookie:
        http-only: true

spring:
  application:
    name: ${GATEWAY_INTERNAL_HOSTNAME:gateway}

  security:
    oauth2:
      client:
        provider:
          keycloak:
            # Public (e.g. Browser) communication with Keycloak
            authorization-uri: >-
              http://${HOST_NAME:localhost}:${KEYCLOAK_HOST_PORT:8180}/realms/coolture-dev/protocol/openid-connect/auth
            # Backend communication with Keycloak (inside private network or when developing locally INTERNAL_HOSTNAME == HOSTNAME)
            token-uri: http://${KEYCLOAK_CONNECT_HOSTNAME:keycloak}:${KEYCLOAK_CONNECT_PORT:8180}/realms/coolture-dev/protocol/openid-connect/token
            jwk-set-uri: http://${KEYCLOAK_CONNECT_HOSTNAME:keycloak}:${KEYCLOAK_CONNECT_PORT:8180}/realms/coolture-dev/protocol/openid-connect/certs
            user-info-uri: http://${KEYCLOAK_CONNECT_HOSTNAME:keycloak}:${KEYCLOAK_CONNECT_PORT:8180}/realms/coolture-dev/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_COOLTURE_GATEWAY_CLIENT_ID}
            client-secret: ${KEYCLOAK_COOLTURE_GATEWAY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://${HOST_NAME}:${GATEWAY_HOST_PORT:8090}/login/oauth2/code/{registrationId}
            scope:
              - openid
              - profile
              - email
              - roles

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: api
              uri: http://${REST_API_CONNECT_HOSTNAME:localhost}:${REST_API_CONNECT_PORT:8081}
              predicates:
                - Path=/api/**
              filters:
                - TokenRelay=
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - RemoveRequestHeader=Cookie
            - id: s3
              uri: http://${GARAGE_API_CONNECT_HOSTNAME:localhost}:${GARAGE_API_CONNECT_PORT:3900}
              predicates:
                - Path=/${GARAGE_BUCKET_NAME:coolture-bucket}/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - RemoveRequestHeader=Cookie

app:
  allowed-origins: >
    http://${HOST_NAME:localhost}:${GATEWAY_HOST_PORT:8090},
    http://${HOST_NAME:localhost}:${REST_API_HOST_PORT:8091},
    http://${HOST_NAME:localhost}:${GARAGE_API_HOST_PORT:3900},
    http://${HOST_NAME:localhost}:${KEYCLOAK_HOST_PORT:8180},
    http://${HOST_NAME:localhost}:${FRONTEND_HOST_PORT:4200}
  frontend:
    redirect-uri: "http://${HOST_NAME:localhost}:${FRONTEND_HOST_PORT:4200}/"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE