spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/coolture-dev
        registration:
          keycloak:
            client-id: coolture-gateway
            client-secret: ${KEYCLOAK_COOLTURE_GATEWAY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
              - roles

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: api
              uri: http://localhost:8081
              predicates:
                - Path=/api/**
              filters:
                - TokenRelay=
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - RemoveRequestHeader=Cookie
            - id: s3
              uri: http://localhost:3900
              predicates:
                - Path=/${GARAGE_BUCKET_NAME}/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - RemoveRequestHeader=Cookie