spring:
  web:
    error:
      include-exception: true
      include-stacktrace: always
      include-message: always
      include-binding-errors: always

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:coolture_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/coolture-dev
          jwk-set-uri: http://localhost:8180/realms/coolture-dev/protocol/openid-connect/certs

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

storage:
  s3:
    endpoint: http://localhost:${GARAGE_API_HOST_PORT}
    region: garage
    access-key: ${GARAGE_ACCESS_KEY_ID}
    secret-key: ${GARAGE_ACCESS_KEY_SECRET}
    bucket-name: ${GARAGE_BUCKET_NAME}
