spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/coolture-dev
          jwk-set-uri: http://keycloak:8180/realms/coolture-dev/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://postgres:${POSTGRES_HOST_PORT:5432}/${POSTGRES_DB:coolture_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

storage:
  s3:
    endpoint: http://s3garage:${GARAGE_API_HOST_PORT}
    region: garage
    access-key: ${GARAGE_ACCESS_KEY_ID}
    secret-key: ${GARAGE_ACCESS_KEY_SECRET}
    bucket-name: ${GARAGE_BUCKET_NAME}
