spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/coolture-dev
          jwk-set-uri: http://localhost:8180/realms/coolture-dev/protocol/openid-connect/certs

env:
  keycloak:
    client-id: ${KEYCLOAK_CLIENT_ID:coolture-gateway}

