spring:
  web:
    error:
      include-exception: true
      include-stacktrace: always
      include-message: always
      include-binding-errors: always

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    root: INFO
    web: DEBUG
    pl.coolture: DEBUG