server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: rest-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

management:
  endpoints:
    web:
      exposure:
        include: [health, info]

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    oauth2RedirectUrl: http://${HOSTNAME:localhost}:${GATEWAY_HOST_PORT:8090}/api/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: ${KEYCLOAK_COOLTURE_SWAGGER_CLIENT_ID}
      client-secret: ${KEYCLOAK_COOLTURE_SWAGGER_CLIENT_SECRET}
      use-pkce-with-authorization-code-grant: true

logging:
  level:
    root: INFO
    web: DEBUG
    pl.coolture: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: TRACE

env:
  host:
    addr: ${HOSTNAME:localhost}
    gateway-port: ${GATEWAY_HOST_PORT:8090}
    rest-api-port: ${REST_API_HOST_PORT:8091}
  keycloak:
    client-id: ${KEYCLOAK_COOLTURE_GATEWAY_CLIENT_ID}
    open-id-url: http://${HOSTNAME:localhost}:${KEYCLOAK_HOST_PORT:8180}/realms/coolture-dev/protocol/openid-connect/
