#!/bin/bash

INPUT_FILE="coolture-dev-realm.json"
OUTPUT_FILE="cleaned-coolture-dev-realm.json"

mkdir -p "$(dirname "$OUTPUT_FILE")"

# Remove IDs to avoid conflicts with autogenerated ones
# Remove RSA keys, also autogenerated every time
# Remove notBefore timestamp
jq '
  walk(if type == "object" then del(.id, .containerId, .notBefore, .keys) else . end)
' < "$INPUT_FILE" > "$OUTPUT_FILE"

if [ $? -eq 0 ]; then
    echo "Minimal export saved to $OUTPUT_FILE"
else
    echo "Error: jq processing failed."
    exit 1
fi